### ISSUE TITLE
Bug: can't build clinker after parser changes in Dao

### ISSUE THREAD

**Issue by dumblob** [daokoder/dao-modules#73]

**Comment by daokoder** [comment]
Fixed.

**Comment by dumblob** [comment]
Please, sync the `dao-modules` repository as I'm still getting the following error:
~~~~
cc -ggdb -O0 -DDEBUG -DDAO_WITH_NUMARRAY -DDAO_WITH_DECORATOR -DDAO_WITH_THREAD -DDAO_WITH_CONCURRENT -DDAO_WITH_RESTART -DTARGET_PLAT=\"linux\" -DLINUX=2 -DUNIX=1 -I../../kernel/ -I../auxlib/ -Ilibffi/include/ -Ilibffi/src/x86/ -I. -I../../kernel/ -fPIC -fPIC  -c dao_clinker.c -o DaoMake.Objs/dao_clinker.c.FAA0.o
dao_clinker.c: In function ‘DaoCLoader_Load’:
dao_clinker.c:315:45: warning: implicit declaration of function ‘isalnum’ [-Wimplicit-function-declaration]
  while( pos && (lib->chars[pos-1] == '_' || isalnum( lib->chars[pos-1] )) ) pos -= 1;
                                             ^
dao_clinker.c:354:8: error: ‘DaoParser {aka struct DaoParser}’ has no member named ‘defParser’
  parser->defParser = defparser = DaoVmSpace_AcquireParser( vms );
        ^
dao_clinker.c:369:10: error: too few arguments to function ‘DaoNamespace_MakeFunction’
   func = DaoNamespace_MakeFunction( ns, str->chars, parser );
          ^
In file included from ../../kernel/daoValue.h:40:0,
                 from dao_clinker.c:10:
../../kernel/daoNamespace.h:139:21: note: declared here
 DAO_DLL DaoRoutine* DaoNamespace_MakeFunction( DaoNamespace *self, const char *proto, DaoParser *parser, DaoParser *defparser );
                     ^
Makefile:38: recipe for target 'DaoMake.Objs/dao_clinker.c.FAA0.o' failed
~~~~
